### PR TITLE
Battle fixes

### LINKED ISSUE #17: Active combat continues even if all enemies are defeated
Right now, if all enemies are defeated during a combat round, the combat round continues playing out with attacks and defenses even though all enemies are defeated. 

The combat round should end when all enemies are defeated.

### PR DESCRIPTION
**Pull request by rooooooooob**
* Fixes #17

* Fixes issue introduced in #11 when entering repeated battles

* Balances defense vs attack abilities

* Show average (5x) damage amount instead of base (1x)

* Add projectile animations + allow AOE attacks to resolve at the same instead of sequentially, reducing animation time.

### CODE REVIEW

File: phaser/src/menus/battle.ts [hunk 1]
```diff
@@ -96,15 +135,15 @@ export class ActiveBattle extends Phaser.Scene {
                     });
                 }),
                 onUseAbility: (abilityIndex: number, energy?: number) => new Promise((resolve) => {
-                    const abilityIcons = this.abilityIcons[abilityIndex];
+                    const abilityIcons = this.abilityIcons[abilityIndex]
```
Comment (rooooooooob) [inline phaser/src/menus/battle.ts:138]: Not sure why this got removed, I'll add it back

File: phaser/src/menus/battle.ts [hunk 2]
```diff
@@ -96,15 +135,15 @@ export class ActiveBattle extends Phaser.Scene {
...
                     this.tweens.add({
                         targets: abilityIcons,
                         y: abilityInUseY(),
                         delay: 150,
                         duration: 250,
                         onComplete: () => {
                             this.tweens.add({
-                                targets: energy !== undefined ? abilityIcons.energyEffectUI[energy] : abilityIcons.baseEffectUI,
+                                targets: energy != undefined ? abilityIcons.energyEffectUI[energy] : abilityIcons.baseEffectUI,
```
Comment (rooooooooob) [inline phaser/src/menus/battle.ts:146]: Not sure why this changed, maybe it was from git stashing before #11
